### ISSUE TITLE
Crash on iOS device

### ISSUE THREAD

**Issue by ayodelekehinde** [kalinjul/EasyQRScan#1]
Nice library!
When I ran it on iOS device i got the following exception:
`Uncaught Kotlin exception: kotlin.IllegalStateException: Size(1242 x 2147483647) is out of range. Each dimension must be between 0 and 16777215.`

I noticed I have to provide a size to the Scanner to avoid that crash.

Ran it on iPhone 11 pro max.

**Comment by kalinjul** [comment]
Thanks for your feedback.
I'm not sure if crashing inside a scrollable component can be considered a user error, so maybe we can fix that issue in the future :)
