### ISSUE TITLE
Library is too big

### ISSUE THREAD

**Issue by abdallahmehiz** [kalinjul/EasyQRScan#12]
Thanks for making such an amazing and easy to use library.

I have used it in a project of mine and the experience have been smooth but one thing that annoyed me is the size.

This is my app's release apk before adding the library:

![2024-10-08-111613_hyprshot](https://github.com/user-attachments/assets/1f7d940f-6813-4540-a915-d5eb27359c88)

And after:

![2024-10-08-111914_hyprshot](https://github.com/user-attachments/assets/0b8d751f-24aa-44c0-b29b-4fd87d96eb78)

As you can see the increase is quite substantial.
And seeing the files responsible for such increase, they're mostly native .so and .tflite files for barcode scanning.

![image](https://github.com/user-attachments/assets/a4e6a374-8785-44b5-9b9e-611b2139b6a4)

My request is to split the library into different parts, each one responsible for scanning one or a few matrix codes. having all of this unnecessary native libraries increase the size is pretty inconvenient.
Thanks.

**Comment by kalinjul** [comment]
Hi, thanks for the nice feedback.
~20Mb increase in size seems heavy, but in fact, the download size is not increased by this amount.
Your APK contains libraries for all different architectures. If you deploy via PlayStore using an app bundle, obviously not all architectures are required.

This library uses the Google Barcode Scanning library on Android.
Google states you should [expect a size increase of 2.4Mb with bundled models](https://developers.google.com/ml-kit/vision/barcode-scanning/android), which is what i have set up by default.

I don't think it's possible to split this up into parts responsible for single types of codes, at least not from my end.
If you don't want the 2.4Mb size increase, you could use an unbundled version of the Barcode Scanning Library.
You'll need to replace the dependency [(using gradle)](https://docs.gradle.org/current/userguide/dependency_downgrade_and_exclude.html#sec:excluding-transitive-deps) i use with
```
  implementation 'com.google.android.gms:play-services-mlkit-barcode-scanning:18.3.1'
```

**Comment by abdallahmehiz** [comment]
I see...
I don't think I'd want to download the barcode models on the fly.
And true, the Play Store install size only increased by around 2mb because of the library.
Thanks for quick response.
![image](https://github.com/user-attachments/assets/3d5ec3e9-db71-4ee8-9ba3-ed54d6a4c944)
