### ISSUE TITLE
Brief Cycan color flash

### ISSUE THREAD

**Issue by ayodelekehinde** [kalinjul/EasyQRScan#3]
There's a brief flash of cyan color when the camera is not ready. And it is hardcoded here:

[This line](https://github.com/kalinjul/EasyQRScan/blob/468d422ac6b274fdbcbd2fa9d5a58fe4d2b454f6/scanner/src/iosMain/kotlin/ScannerView.kt#L82)

**Comment by ayodelekehinde** [comment]
In other news, is there why the android min SDK is 26? are you using any special api that requires that?

**Comment by kalinjul** [comment]
This should be fixed in 0.1.4. Also, i downgraded the min SDK to 21.
