### ISSUE TITLE
Ios problem with compose version 1.6.10+

### ISSUE THREAD

**Issue by benjaminP-h2o** [kalinjul/EasyQRScan#4]
I recently updated my project to use compose-plugin version 1.6.11 and I have issues with the Ios since. It still works, but the camera feed isn't shown on the screen. I only have my background colour which is shown. It stills scans fine, but I don't see anything when doing so. Is there any plans to migrate to version 1.6.10 or higher?

**Comment by kalinjul** [comment]
Hi, thanks for reporting.
I will upgrade to compose 1.6.10 and check.

**Comment by kalinjul** [comment]
This is a problem induced by a fix in compose 1.6.10 (i think).
It's fixed in v 0.1.5 of this library, but you can also just add a size to your Scanner or ScannerWithPermissions (e.g. modifier.fillMaxSize()).
