### ISSUE TITLE
Support for MLKit Barcode and TextRecognizer scanner in ios and android

### ISSUE THREAD

**Issue by yuvaraj119** [kalinjul/EasyQRScan#8]
How can we write the ios MLKit Barcode scanner  and TextRecognizer in KMP?
https://developers.google.com/ml-kit/vision/barcode-scanning/ios#swift

**Comment by kalinjul** [comment]
Well you could write a library that uses the MLKit library?
There's actually support for using CocoaPods in KMP: https://kotlinlang.org/docs/native-cocoapods.html
But there's no place for such things in this project :)
